### ISSUE TITLE
Change Tutorial Video into Youtube Source

### ISSUE THREAD

**Issue by FatwaDwiHidayat** [kulkultech/open-source#68]
I think its better to use Youtube as source of the tutorial video. We can add subtitle and also change video speed into slow/fast.
As far as my analysis, besides being smaller in video size, but Youtube video quality also look more clearer and sharper than Loom.

**Comment by empeje** [comment]
Thanks for another issue, yes after reviewing the subtitle issues, I think YouTube is more viable. We initially use Loom because it helps us record the screen and directly shares it with the internet. But in the Long run, yes, YouTube is more viable.

However, **I want to do it incrementally, so whenever there's new subtitle for a video, I will move the video to YouTube.**

**Comment by FatwaDwiHidayat** [comment]
Yes, I'm on process of making subtitles for another tutorial video. Will be finished soon !

**Comment by empeje** [comment]
Good stuff!

**Comment by empeje** [comment]
Solved in #67 #78 #75
